In [ ]:
!pip install transformers
!pip install sentence-transformers
from sentence_transformers import SentenceTransformer, util
from transformers import pipeline, set_seed
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
model = SentenceTransformer('stsb-roberta-large')

In [ ]:
f1=open("/sample(1).txt","r")
d1=f1.read()
f1.close()
d1

'Validating The Myth of Average through Evidences\nMost formal educational practices based on the classroom, imparts skills and knowledge at scale, by adopting the model of a factory. Here, the focus is on creation of formal processes, mass production of measurable outcomes, and standardization. Curricula and educational practices are designed for a hypothetical ``average" student, having ``average" abilities. However, recent advances in individualization have found vast discrepancies between  individual traits and group averages. Designing models based on group averages, are usually ineffective when the individual is the target beneficiary. This research proposes Evidence Based Competency Model as a mechanism for providing individualized learning experiences. Here, the term evidence, refers to informal data generated by the learner, pertinent to the learning process. Individual models are built for each learner, based on their learning activities. These models are clustered to observe

In [ ]:
f2=open("/sample(2)","r")
d2=f2.read()
f2.close()
d2

'The Myth of Average is a belief that’s been prominent in most sciences and in education. It’s the belief that we can use statistical averages to understand individuals. Scientists have come to realize that it’s a myth, and over the last 10 years have been moving from averages to individuals, so for example we’re hearing a lot of things like ‘personalized medicine.’ Unfortunately, education has not quite realized the myth yet, and so what we have is a situation where not only do we accept the idea of designing something for the individual based on the average, we actually promote it. The myth is that the average is fits for most people, when, in fact, it doesn’t. When it comes to designing environments it hurts us in two ways. As I said in my TEDX talk, the first is that you can be incredibly talented in one area, but average or below average in another. For example, say you’re really gifted in math, but you are an average or below average reader. The way our education system is design

In [ ]:
f3=open("/sample(3)","r")
d3=f3.read()
f3.close()
d3

"In cricket, a player's batting average is the total number of runs they have scored divided by the number of times they have been out, usually given to two decimal places. Since the number of runs a player scores and how often they get out are primarily measures of their own playing ability, and largely independent of their teammates, batting average is a good metric for an individual player's skill as a batter (although the practice of drawing comparisons between players on this basis is not without criticism[1]). The number is also simple to interpret intuitively. If all the batter's innings were completed (i.e. they were out every innings), this is the average number of runs they score per innings. If they did not complete all their innings (i.e. some innings they finished not out), this number is an estimate of the unknown average number of runs they score per innings.Each player normally has several batting averages, with a different figure calculated for each type of match they 

In [ ]:
embedding1 = model.encode(d1, convert_to_tensor=True)
embedding2 = model.encode(d2, convert_to_tensor=True)
embedding3 = model.encode(d3, convert_to_tensor=True)

In [ ]:
cosine_scores1 = util.pytorch_cos_sim(embedding1, embedding2)
cosine_scores2 = util.pytorch_cos_sim(embedding1, embedding3)
cosine_scores3 = util.pytorch_cos_sim(embedding2, embedding3)

In [ ]:
cosine_scores1

tensor([[0.5664]])

In [ ]:
cosine_scores2

tensor([[0.3695]])

In [ ]:
cosine_scores3

tensor([[0.4137]])

In [ ]:
cosine_scores4 = util.pytorch_cos_sim(embedding1, embedding1)
cosine_scores4

tensor([[1.]])

In [ ]:
s4="Validating the myth of Average"
embedding4 = model.encode(s4, convert_to_tensor=True)
cosine_scores7 = util.pytorch_cos_sim(embedding1, embedding4)
cosine_scores8 = util.pytorch_cos_sim(embedding2, embedding4)
cosine_scores9 = util.pytorch_cos_sim(embedding3, embedding4)

In [ ]:
cosine_scores7

tensor([[0.3448]])

In [ ]:
cosine_scores8

tensor([[0.3034]])

In [ ]:
len(d3)

3207

In [ ]:
d1=d1[:len(d3)]
generator = pipeline('text-generation', model='gpt2')
set_seed(42)
d10=generator(d1, max_length=1000, num_return_sequences=1)[0]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
d11=d10['generated_text']

d1

'Validating The Myth of Average through Evidences\nMost formal educational practices based on the classroom, imparts skills and knowledge at scale, by adopting the model of a factory. Here, the focus is on creation of formal processes, mass production of measurable outcomes, and standardization. Curricula and educational practices are designed for a hypothetical ``average" student, having ``average" abilities. However, recent advances in individualization have found vast discrepancies between  ind'

In [ ]:
d11

'Validating The Myth of Average through Evidences\nMost formal educational practices based on the classroom, imparts skills and knowledge at scale, by adopting the model of a factory. Here, the focus is on creation of formal processes, mass production of measurable outcomes, and standardization. Curricula and educational practices are designed for a hypothetical ``average" student, having ``average" abilities. However, recent advances in individualization have found vast discrepancies between  indy and high school graduates. In this series, I will argue empirically and methodically that the \xa0model of a factory is wrong. In doing so, I provide a critical examination of the theory of typical education as applied to students in both the middle and high school levels. As a result, I take the role of a researcher in the field of education, with an emphasis on a range of fields including, but not limited to, biology, anthropology, mathematics, economics, social science, art, sociology, so

In [ ]:
d11=d11[len(d1):len(d11)]
d11

"y and high school graduates. In this series, I will argue empirically and methodically that the \xa0model of a factory is wrong. In doing so, I provide a critical examination of the theory of typical education as applied to students in both the middle and high school levels. As a result, I take the role of a researcher in the field of education, with an emphasis on a range of fields including, but not limited to, biology, anthropology, mathematics, economics, social science, art, sociology, sociology and environmental psychology. This will provide a thorough introduction to this work.\nIn Chapter 1 of this book, the title is the title of a speech I gave at the American Psychological Association National Convention in February 2005 entitled ``On Accumulation and Evaluation: A Practical Perspective''. The title is derived from the British model of the ``acceleration of success.'' This means, in my judgment the goal would be to demonstrate empirically that the achievement rate (in our vi

In [ ]:
embedding5 = model.encode(d11, convert_to_tensor=True)

In [ ]:
cosine_scores10 = util.pytorch_cos_sim(embedding5, embedding1)
cosine_scores10

tensor([[0.5434]])